// Generated by CoffeeScript 2.7.0
/* Pressure Conversions */

var atm$bar, atm$pas, atm$psi, atm$tor, bar$atm, bar$pas, bar$psi, bar$tor, convertPressure, pas$atm, pas$bar, pas$psi, pas$tor, psi$atm, psi$bar, psi$pas, psi$tor, tor$atm, tor$bar, tor$pas, tor$psi;

convertPressure = {
  bar: {},
  pascal: {},
  standardAtmospheric: {},
  poundSquareInch: {},
  torr: {}
};

/* Bar Conversions */
convertPressure.bar.pascal = bar$pas = function(bar) {
  return bar * 1e+5; // Bars to Pascals
};

convertPressure.bar.standardAtmospheric = bar$atm = function(bar) {
  return bar / 1.013; // Bars to Standard Atmospheric Pressure
};

convertPressure.bar.poundSquareInch = bar$psi = function(bar) {
  return bar * 14.504; // Bars to Pounds per Square Inch
};

convertPressure.bar.torr = bar$tor = function(bar) {
  return bar * 750.1; // Bars to Torrs
};

/* Pascal Conversions */
convertPressure.pascal.bar = pas$bar = function(pas) {
  return pas / 1e+5; // Pascals to Bars
};

convertPressure.pascal.standardAtmospheric = pas$atm = function(pas) {
  return pas / 1013e+2; // Pascals to Standard Atmospheric Pressure
};

convertPressure.pascal.poundSquareInch = pas$psi = function(pas) {
  return pas / 6895; // Pascals to Pounds per Square Inch
};

convertPressure.pascal.torr = pas$tor = function(pas) {
  return pas / 133.3; // Pascals to Torrs
};

/* Standard Atmospheric Pressure Conversions */
convertPressure.standardAtmospheric.bar = atm$bar = function(atm) {
  return atm * 1.013; // Standard Atmospheric Pressure to Bars
};

convertPressure.standardAtmospheric.pascal = atm$pas = function(atm) {
  return atm * 1013e+2; // Standard Atmospheric Pressure to Pascals
};

convertPressure.standardAtmospheric.poundSquareInch = atm$psi = function(atm) {
  return atm * 14.696; // Standard Atmospheric Pressure to Pounds per Square Inch
};

convertPressure.standardAtmospheric.torr = atm$tor = function(atm) {
  return atm * 76e+1; // Standard Atmospheric Pressure to Torrs
};

/* Pounds per Square Inch Conversions */
convertPressure.poundSquareInch.bar = psi$bar = function(psi) {
  return psi / 14.504; // Pounds per Square Inch to Bars
};

convertPressure.poundSquareInch.pascal = psi$pas = function(psi) {
  return psi * 6895; // Pounds per Square Inch to Pascals
};

convertPressure.poundSquareInch.standardAtmospheric = psi$atm = function(psi) {
  return psi / 14.696; // Pounds per Square Inch to Standard Atmospheric Pressure
};

convertPressure.poundSquareInch.torr = psi$tor = function(psi) {
  return psi * 51.715; // Pounds per Square Inch to Torrs
};

/* Torr Conversions */
convertPressure.torr.bar = tor$bar = function(tor) {
  return tor / 750.1; // Torrs to Bars
};

convertPressure.torr.pascal = tor$pas = function(tor) {
  return tor * 133.3; // Torrs to Pascals
};

convertPressure.torr.standardAtmospheric = tor$atm = function(tor) {
  return tor / 76e+1; // Torrs to Standard Atmospheric Pressure
};

convertPressure.torr.poundSquareInch = tor$psi = function(tor) {
  return tor / 51.715; // Torrs to Pounds per Square Inch
};