// Generated by CoffeeScript 2.7.0
/* Mass Conversions */

var cg$dag, cg$dg, cg$g, cg$hg, cg$kg, cg$lb, cg$mg, cg$ng, cg$oz, cg$st, cg$t, cg$ug, convertMass, dag$cg, dag$dg, dag$g, dag$hg, dag$kg, dag$lb, dag$mg, dag$ng, dag$oz, dag$st, dag$t, dag$ug, dg$cg, dg$dag, dg$g, dg$hg, dg$kg, dg$lb, dg$mg, dg$ng, dg$oz, dg$st, dg$t, dg$ug, g$cg, g$dag, g$dg, g$hg, g$kg, g$lb, g$mg, g$ng, g$oz, g$st, g$t, g$ug, hg$cg, hg$dag, hg$dg, hg$g, hg$kg, hg$lb, hg$mg, hg$ng, hg$oz, hg$st, hg$t, hg$ug, kg$cg, kg$dag, kg$dg, kg$g, kg$hg, kg$lb, kg$mg, kg$ng, kg$oz, kg$st, kg$t, kg$ug, lb$cg, lb$dag, lb$dg, lb$g, lb$hg, lb$kg, lb$mg, lb$ng, lb$oz, lb$st, lb$t, lb$ug, mg$cg, mg$dag, mg$dg, mg$g, mg$hg, mg$kg, mg$lb, mg$ng, mg$oz, mg$st, mg$t, mg$ug, ng$cg, ng$dag, ng$dg, ng$g, ng$hg, ng$kg, ng$lb, ng$mg, ng$oz, ng$st, ng$t, ng$ug, oz$cg, oz$dag, oz$dg, oz$g, oz$hg, oz$kg, oz$lb, oz$mg, oz$ng, oz$st, oz$t, oz$ug, st$cg, st$dag, st$dg, st$g, st$hg, st$kg, st$lb, st$mg, st$ng, st$oz, st$t, st$ug, t$cg, t$dag, t$dg, t$g, t$hg, t$kg, t$lb, t$mg, t$ng, t$oz, t$st, t$ug, ug$cg, ug$dag, ug$dg, ug$g, ug$hg, ug$kg, ug$lb, ug$mg, ug$ng, ug$oz, ug$st, ug$t;

convertMass = {
  nanogram: {},
  microgram: {},
  milligram: {},
  centigram: {},
  decigram: {},
  gram: {},
  decagram: {},
  hectogram: {},
  kilogram: {},
  ounce: {},
  pound: {},
  stone: {},
  ton: {}
};

/* Nanogram Conversions */
convertMass.nanogram.microgram = ng$ug = function(ng) {
  return ng / 1e+3; // Nanogram to Microgram
};

convertMass.nanogram.milligram = ng$mg = function(ng) {
  return ng / 1e+6; // Nanogram to Milligram
};

convertMass.nanogram.centigram = ng$cg = function(ng) {
  return ng / 1e+7; // Nanogram to Centigram
};

convertMass.nanogram.decigram = ng$dg = function(ng) {
  return ng / 1e+8; // Nanogram to Decigram
};

convertMass.nanogram.gram = ng$g = function(ng) {
  return ng / 1e+9; // Nanogram to Gram
};

convertMass.nanogram.decagram = ng$dag = function(ng) {
  return ng / 1e+10; // Nanogram to Decagram
};

convertMass.nanogram.hectogram = ng$hg = function(ng) {
  return ng / 1e+11; // Nanogram to Hectogram
};

convertMass.nanogram.kilogram = ng$kg = function(ng) {
  return ng / 1e+12; // Nanogram to Kilogram
};

convertMass.nanogram.ounce = ng$oz = function(ng) {
  return ng / 2835e+7; // Nanogram to Ounce
};

convertMass.nanogram.pound = ng$lb = function(ng) {
  return ng / 4536e+8; // Nanogram to Pound
};

convertMass.nanogram.stone = ng$st = function(ng) {
  return ng / 635e+10; // Nanogram to Stone
};

convertMass.nanogram.ton = ng$t = function(ng) {
  return ng / 9072e+11; // Nanogram to Ton
};

/* Microgram Conversions */
convertMass.microgram.nanogram = ug$ng = function(ug) {
  return ug * 1e+3; // Microgram to Nanogram
};

convertMass.microgram.milligram = ug$mg = function(ug) {
  return ug / 1e+3; // Microgram to Milligram
};

convertMass.microgram.centigram = ug$cg = function(ug) {
  return ug / 1e+4; // Microgram to Centigram
};

convertMass.microgram.decigram = ug$dg = function(ug) {
  return ug / 1e+5; // Microgram to Decigram
};

convertMass.microgram.gram = ug$g = function(ug) {
  return ug / 1e+6; // Microgram to Gram
};

convertMass.microgram.decagram = ug$dag = function(ug) {
  return ug / 1e+7; // Microgram to Decagram
};

convertMass.microgram.hectogram = ug$hg = function(ug) {
  return ug / 1e+8; // Microgram to Hectogram
};

convertMass.microgram.kilogram = ug$kg = function(ug) {
  return ug / 1e+9; // Microgram to Kilogram
};

convertMass.microgram.ounce = ug$oz = function(ug) {
  return ug / 2835e+4; // Microgram to Ounce
};

convertMass.microgram.pound = ug$lb = function(ug) {
  return ug / 4536e+5; // Microgram to Pound
};

convertMass.microgram.stone = ug$st = function(ug) {
  return ug / 635e+7; // Microgram to Stone
};

convertMass.microgram.ton = ug$t = function(ug) {
  return ug / 9072e+8; // Microgram to Ton
};

/* Milligram Conversions */
convertMass.milligram.nanogram = mg$ng = function(mg) {
  return mg * 1e+6; // Milligram to Nanogram
};

convertMass.milligram.microgram = mg$ug = function(mg) {
  return mg * 1e+3; // Milligram to Microgram
};

convertMass.milligram.centigram = mg$cg = function(mg) {
  return mg / 1e+1; // Milligram to Centigram
};

convertMass.milligram.decigram = mg$dg = function(mg) {
  return mg / 1e+2; // Milligram to Decigram
};

convertMass.milligram.gram = mg$g = function(mg) {
  return mg / 1e+3; // Milligram to Gram
};

convertMass.milligram.decagram = mg$dag = function(mg) {
  return mg / 1e+4; // Milligram to Decagram
};

convertMass.milligram.hectogram = mg$hg = function(mg) {
  return mg / 1e+5; // Milligram to Hectogram
};

convertMass.milligram.kilogram = mg$kg = function(mg) {
  return mg / 1e+6; // Milligram to Kilogram
};

convertMass.milligram.ounce = mg$oz = function(mg) {
  return mg / 2835e+1; // Milligram to Ounce
};

convertMass.milligram.pound = mg$lb = function(mg) {
  return mg / 4536e+2; // Milligram to Pound
};

convertMass.milligram.stone = mg$st = function(mg) {
  return mg / 635e+4; // Milligram to Stone
};

convertMass.milligram.ton = mg$t = function(mg) {
  return mg / 9072e+5; // Milligram to Ton
};

/* Centigram Conversions */
convertMass.centigram.nanogram = cg$ng = function(cg) {
  return cg * 1e+7; // Centigram to Nanogram
};

convertMass.centigram.microgram = cg$ug = function(cg) {
  return cg * 1e+4; // Centigram to Microgram
};

convertMass.centigram.milligram = cg$mg = function(cg) {
  return cg * 1e+1; // Centigram to Milligram
};

convertMass.centigram.decigram = cg$dg = function(cg) {
  return cg / 1e+1; // Centigram to Decigram
};

convertMass.centigram.gram = cg$g = function(cg) {
  return cg / 1e+2; // Centigram to Gram
};

convertMass.centigram.decagram = cg$dag = function(cg) {
  return cg / 1e+3; // Centigram to Decagram
};

convertMass.centigram.hectogram = cg$hg = function(cg) {
  return cg / 1e+4; // Centigram to Hectogram
};

convertMass.centigram.kilogram = cg$kg = function(cg) {
  return cg / 1e+5; // Centigram to Kilogram
};

convertMass.centigram.ounce = cg$oz = function(cg) {
  return cg / 2835; // Centigram to Ounce
};

convertMass.centigram.pound = cg$lb = function(cg) {
  return cg / 4536e+1; // Centigram to Pound
};

convertMass.centigram.stone = cg$st = function(cg) {
  return cg / 635e+3; // Centigram to Stone
};

convertMass.centigram.ton = cg$t = function(cg) {
  return cg / 9072e+4; // Centigram to Ton
};

/* Decigram Conversions */
convertMass.decigram.nanogram = dg$ng = function(dg) {
  return dg * 1e+8; // Decigram to Nanogram
};

convertMass.decigram.microgram = dg$ug = function(dg) {
  return dg * 1e+5; // Decigram to Microgram
};

convertMass.decigram.milligram = dg$mg = function(dg) {
  return dg * 1e+2; // Decigram to Milligram
};

convertMass.decigram.centigram = dg$cg = function(dg) {
  return dg * 1e+1; // Decigram to Centigram
};

convertMass.decigram.gram = dg$g = function(dg) {
  return dg / 1e+1; // Decigram to Gram
};

convertMass.decigram.decagram = dg$dag = function(dg) {
  return dg / 1e+2; // Decigram to Decagram
};

convertMass.decigram.hectogram = dg$hg = function(dg) {
  return dg / 1e+3; // Decigram to Hectogram
};

convertMass.decigram.kilogram = dg$kg = function(dg) {
  return dg / 1e+4; // Decigram to Kilogram
};

convertMass.decigram.ounce = dg$oz = function(dg) {
  return dg / 283.5; // Decigram to Ounce
};

convertMass.decigram.pound = dg$lb = function(dg) {
  return dg / 4536; // Decigram to Pound
};

convertMass.decigram.stone = dg$st = function(dg) {
  return dg / 635e+2; // Decigram to Stone
};

convertMass.decigram.ton = dg$t = function(dg) {
  return dg / 9072e+3; // Decigram to Ton
};

/* Gram Conversions */
convertMass.gram.nanogram = g$ng = function(g) {
  return g * 1e+9; // Gram to Nanogram
};

convertMass.gram.microgram = g$ug = function(g) {
  return g * 1e+6; // Gram to Microgram
};

convertMass.gram.milligram = g$mg = function(g) {
  return g * 1e+3; // Gram to Milligram
};

convertMass.gram.centigram = g$cg = function(g) {
  return g * 1e+2; // Gram to Centigram
};

convertMass.gram.decigram = g$dg = function(g) {
  return g * 1e+1; // Gram to Decigram
};

convertMass.gram.decagram = g$dag = function(g) {
  return g / 1e+1; // Gram to Decagram
};

convertMass.gram.hectogram = g$hg = function(g) {
  return g / 1e+2; // Gram to Hectogram
};

convertMass.gram.kilogram = g$kg = function(g) {
  return g / 1e+3; // Gram to Kilogram
};

convertMass.gram.ounce = g$oz = function(g) {
  return g / 28.35; // Gram to Ounce
};

convertMass.gram.pound = g$lb = function(g) {
  return g / 453.6; // Gram to Pound
};

convertMass.gram.stone = g$st = function(g) {
  return g / 635e+1; // Gram to Stone
};

convertMass.gram.ton = g$t = function(g) {
  return g / 9072e+2; // Gram to Ton
};

/* Decagram Conversions */
convertMass.decagram.nanogram = dag$ng = function(dag) {
  return dag * 1e+10; // Decagram to Nanogram
};

convertMass.decagram.microgram = dag$ug = function(dag) {
  return dag * 1e+7; // Decagram to Microgram
};

convertMass.decagram.milligram = dag$mg = function(dag) {
  return dag * 1e+4; // Decagram to Milligram
};

convertMass.decagram.centigram = dag$cg = function(dag) {
  return dag * 1e+3; // Decagram to Centigram
};

convertMass.decagram.decigram = dag$dg = function(dag) {
  return dag * 1e+2; // Decagram to Decigram
};

convertMass.decagram.gram = dag$g = function(dag) {
  return dag * 1e+1; // Decagram to Gram
};

convertMass.decagram.hectogram = dag$hg = function(dag) {
  return dag / 1e+1; // Decagram to Hectogram
};

convertMass.decagram.kilogram = dag$kg = function(dag) {
  return dag / 1e+2; // Decagram to Kilogram
};

convertMass.decagram.ounce = dag$oz = function(dag) {
  return dag / 2.835; // Decagram to Ounce
};

convertMass.decagram.pound = dag$lb = function(dag) {
  return dag / 45.36; // Decagram to Pound
};

convertMass.decagram.stone = dag$st = function(dag) {
  return dag / 635; // Decagram to Stone
};

convertMass.decagram.ton = dag$t = function(dag) {
  return dag / 9072e+1; // Decagram to Ton
};

/* Hectogram Conversions */
convertMass.hectogram.nanogram = hg$ng = function(hg) {
  return hg * 1e+11; // Hectogram to Nanogram
};

convertMass.hectogram.microgram = hg$ug = function(hg) {
  return hg * 1e+8; // Hectogram to Microgram
};

convertMass.hectogram.milligram = hg$mg = function(hg) {
  return hg * 1e+5; // Hectogram to Milligram
};

convertMass.hectogram.centigram = hg$cg = function(hg) {
  return hg * 1e+4; // Hectogram to Centigram
};

convertMass.hectogram.decigram = hg$dg = function(hg) {
  return hg * 1e+3; // Hectogram to Decigram
};

convertMass.hectogram.gram = hg$g = function(hg) {
  return hg * 1e+2; // Hectogram to Gram
};

convertMass.hectogram.decagram = hg$dag = function(hg) {
  return hg * 1e+1; // Hectogram to Decagram
};

convertMass.hectogram.kilogram = hg$kg = function(hg) {
  return hg / 1e+1; // Hectogram to Kilogram
};

convertMass.hectogram.ounce = hg$oz = function(hg) {
  return hg * 3.5274; // Hectogram to Ounce
};

convertMass.hectogram.pound = hg$lb = function(hg) {
  return hg / 4.536; // Hectogram to Pound
};

convertMass.hectogram.stone = hg$st = function(hg) {
  return hg / 63.5; // Hectogram to Stone
};

convertMass.hectogram.ton = hg$t = function(hg) {
  return hg / 9072; // Hectogram to Ton
};

/* Kilogram Conversions */
convertMass.kilogram.nanogram = kg$ng = function(kg) {
  return kg * 1e+12; // Kilogram to Nanogram
};

convertMass.kilogram.microgram = kg$ug = function(kg) {
  return kg * 1e+9; // Kilogram to Microgram
};

convertMass.kilogram.milligram = kg$mg = function(kg) {
  return kg * 1e+6; // Kilogram to Milligram
};

convertMass.kilogram.centigram = kg$cg = function(kg) {
  return kg * 1e+5; // Kilogram to Centigram
};

convertMass.kilogram.decigram = kg$dg = function(kg) {
  return kg * 1e+4; // Kilogram to Decigram
};

convertMass.kilogram.gram = kg$g = function(kg) {
  return kg * 1e+3; // Kilogram to Gram
};

convertMass.kilogram.decagram = kg$dag = function(kg) {
  return kg * 1e+2; // Kilogram to Decagram
};

convertMass.kilogram.hectogram = kg$hg = function(kg) {
  return kg * 1e+1; // Kilogram to Hectogram
};

convertMass.kilogram.ounce = kg$oz = function(kg) {
  return kg * 35.274; // Kilogram to Ounce
};

convertMass.kilogram.pound = kg$lb = function(kg) {
  return kg * 2.205; // Kilogram to Pound
};

convertMass.kilogram.stone = kg$st = function(kg) {
  return kg / 6.35; // Kilogram to Stone
};

convertMass.kilogram.ton = kg$t = function(kg) {
  return kg / 907.2; // Kilogram to Ton
};

/* Ounce Conversions */
convertMass.ounce.nanogram = oz$ng = function(oz) {
  return oz * 2835e+7; // Ounce to Nanogram
};

convertMass.ounce.microgram = oz$ug = function(oz) {
  return oz * 2835e+4; // Ounce to Microgram
};

convertMass.ounce.milligram = oz$mg = function(oz) {
  return oz * 2835e+1; // Ounce to Milligram
};

convertMass.ounce.centigram = oz$cg = function(oz) {
  return oz * 2835; // Ounce to Centigram
};

convertMass.ounce.decigram = oz$dg = function(oz) {
  return oz * 283.5; // Ounce to Decigram
};

convertMass.ounce.gram = oz$g = function(oz) {
  return oz * 28.35; // Ounce to Gram
};

convertMass.ounce.decagram = oz$dag = function(oz) {
  return oz * 2.835; // Ounce to Decagram
};

convertMass.ounce.hectogram = oz$hg = function(oz) {
  return oz / 3.5274; // Ounce to Hectogram
};

convertMass.ounce.kilogram = oz$kg = function(oz) {
  return oz / 35.274; // Ounce to Kilogram
};

convertMass.ounce.pound = oz$lb = function(oz) {
  return oz / 16; // Ounce to Pound
};

convertMass.ounce.stone = oz$st = function(oz) {
  return oz / 224; // Ounce to Stone
};

convertMass.ounce.ton = oz$t = function(oz) {
  return oz / 32e+3; // Ounce to Ton
};

/* Pound Conversions */
convertMass.pound.nanogram = lb$ng = function(lb) {
  return lb * 4536e+8; // Pound to Nanogram
};

convertMass.pound.microgram = lb$ug = function(lb) {
  return lb * 4536e+5; // Pound to Microgram
};

convertMass.pound.milligram = lb$mg = function(lb) {
  return lb * 4536e+2; // Pound to Milligram
};

convertMass.pound.centigram = lb$cg = function(lb) {
  return lb * 4536e+1; // Pound to Centigram
};

convertMass.pound.decigram = lb$dg = function(lb) {
  return lb * 4536; // Pound to Decigram
};

convertMass.pound.gram = lb$g = function(lb) {
  return lb * 453.6; // Pound to Gram
};

convertMass.pound.decagram = lb$dag = function(lb) {
  return lb * 45.36; // Pound to Decagram
};

convertMass.pound.hectogram = lb$hg = function(lb) {
  return lb * 4.536; // Pound to Hectogram
};

convertMass.pound.kilogram = lb$kg = function(lb) {
  return lb / 2.205; // Pound to Kilogram
};

convertMass.pound.ounce = lb$oz = function(lb) {
  return lb * 16; // Pound to Ounce
};

convertMass.pound.stone = lb$st = function(lb) {
  return lb / 14; // Pound to Stone
};

convertMass.pound.ton = lb$t = function(lb) {
  return lb / 2205; // Pound to Ton
};

/* Stone Conversions */
convertMass.stone.nanogram = st$ng = function(st) {
  return st * 635e+10; // Stone to Nanogram
};

convertMass.stone.microgram = st$ug = function(st) {
  return st * 635e+7; // Stone to Microgram
};

convertMass.stone.milligram = st$mg = function(st) {
  return st * 635e+4; // Stone to Milligram
};

convertMass.stone.centigram = st$cg = function(st) {
  return st * 635e+3; // Stone to Centigram
};

convertMass.stone.decigram = st$dg = function(st) {
  return st * 635e+2; // Stone to Decigram
};

convertMass.stone.gram = st$g = function(st) {
  return st * 635e+1; // Stone to Gram
};

convertMass.stone.decagram = st$dag = function(st) {
  return st * 635; // Stone to Decagram
};

convertMass.stone.hectogram = st$hg = function(st) {
  return st * 63.5; // Stone to Hectogram
};

convertMass.stone.kilogram = st$kg = function(st) {
  return st * 6.35; // Stone to Kilogram
};

convertMass.stone.ounce = st$oz = function(st) {
  return st * 224; // Stone to Ounce
};

convertMass.stone.pound = st$lb = function(st) {
  return st * 14; // Stone to Pound
};

convertMass.stone.ton = st$t = function(st) {
  return st / 157.5; // Stone to Ton
};

/* Ton Conversions */
convertMass.ton.nanogram = t$ng = function(t) {
  return t * 9072e+11; // Ton to Nanogram
};

convertMass.ton.microgram = t$ug = function(t) {
  return t * 9072e+8; // Ton to Microgram
};

convertMass.ton.milligram = t$mg = function(t) {
  return t * 9072e+5; // Ton to Milligram
};

convertMass.ton.centigram = t$cg = function(t) {
  return t * 9072e+4; // Ton to Centigram
};

convertMass.ton.decigram = t$dg = function(t) {
  return t * 9072e+3; // Ton to Decigram
};

convertMass.ton.gram = t$g = function(t) {
  return t * 9072e+2; // Ton to Gram
};

convertMass.ton.decagram = t$dag = function(t) {
  return t * 9072e+1; // Ton to Decagram
};

convertMass.ton.hectogram = t$hg = function(t) {
  return t * 9072; // Ton to Hectogram
};

convertMass.ton.kilogram = t$kg = function(t) {
  return t * 907.2; // Ton to Kilogram
};

convertMass.ton.ounce = t$oz = function(t) {
  return t * 32e+3; // Ton to Ounce
};

convertMass.ton.pound = t$lb = function(t) {
  return t * 2205; // Ton to Pound
};

convertMass.ton.stone = t$st = function(t) {
  return t * 157.5; // Ton to Stone
};