// Generated by CoffeeScript 2.7.0
/* Temperature Conversions */

var c$f, c$k, convertTemperature, f$c, f$k, k$c, k$f;

convertTemperature = {
  celsius: {},
  fahrenheit: {},
  kelvin: {}
};

/* Celsius Conversions */
convertTemperature.celsius.fahrenheit = c$f = function(c) {
  return c * (9 / 5) + 32; // Celsius to Fahrenheit
};

convertTemperature.celsius.kelvin = c$k = function(c) {
  return c + 273.15; // Celsius to Kelvin
};

/* Fahrenheit Conversions */
convertTemperature.fahrenheit.celsius = f$c = function(f) {
  return (f - 32) * (5 / 9); // Fahrenheit to Celsius
};

convertTemperature.fahrenheit.kelvin = f$k = function(f) {
  return (f - 32) * (5 / 9) + 273.15; // Fahrenheit to Kelvin
};

/* Kelvin Conversions */
convertTemperature.kelvin.celsius = k$c = function(k) {
  return k - 273.15; // Kelvin to Celsius
};

convertTemperature.kelvin.fahrenheit = k$f = function(k) {
  return (k - 273.15) * (9 / 5) + 32; // Kelvin to Fahrenheit
};