// Generated by CoffeeScript 2.7.0
/* Angle Conversions */

var convertAngle, deg$gad, deg$moa, deg$mrad, deg$rad, deg$soa, gad$deg, gad$moa, gad$mrad, gad$rad, gad$soa, moa$deg, moa$gad, moa$mrad, moa$rad, moa$soa, mrad$deg, mrad$gad, mrad$moa, mrad$rad, mrad$soa, rad$deg, rad$gad, rad$moa, rad$mrad, rad$soa, soa$deg, soa$gad, soa$moa, soa$mrad, soa$rad;

convertAngle = {
  degree: {},
  gradian: {},
  milliradian: {},
  radian: {},
  arcSecond: {},
  arcMinute: {}
};

/* Degree Conversions */
convertAngle.degree.gradian = deg$gad = function(deg) {
  return deg * (200 / 180); // Degree to Gradian
};

convertAngle.degree.milliradian = deg$mrad = function(deg) {
  return deg * ((1000 * Math.PI) / 180); // Degree to Milliradian
};

convertAngle.degree.radian = deg$rad = function(deg) {
  return deg * (Math.PI / 180); // Degree to Radian
};

convertAngle.degree.arcSecond = deg$soa = function(deg) {
  return deg * 3600; // Degree to Second of Arc
};

convertAngle.degree.arcMinute = deg$moa = function(deg) {
  return deg * 60; // Degree to Minute of Arc
};

/* Gradian Conversions */
convertAngle.gradian.degree = gad$deg = function(gad) {
  return gad * (180 / 200); // Gradian to Degree
};

convertAngle.gradian.milliradian = gad$mrad = function(gad) {
  return gad * ((1000 * Math.PI) / 200); // Gradian to Milliradian
};

convertAngle.gradian.radian = gad$rad = function(gad) {
  return gad * (Math.PI / 200); // Gradian to Radian
};

convertAngle.gradian.arcSecond = gad$soa = function(gad) {
  return gad * 3240; // Gradian to Second of Arc
};

convertAngle.gradian.arcMinute = gad$moa = function(gad) {
  return gad * 54; // Gradian to Minute of Arc
};

/* Milliradian Conversions */
convertAngle.milliradian.degree = mrad$deg = function(mrad) {
  return mrad * (180 / (1000 * Math.PI)); // Milliradian to Degree
};

convertAngle.milliradian.gradian = mrad$gad = function(mrad) {
  return mrad * (200 / (1000 * Math.PI)); // Milliradian to Gradian
};

convertAngle.milliradian.radian = mrad$rad = function(mrad) {
  return mrad / 1000; // Milliradian to Radian
};

convertAngle.milliradian.arcSecond = mrad$soa = function(mrad) {
  return mrad * ((180 * 3600) / (1000 * Math.PI)); // Milliradian to Second of Arc
};

convertAngle.milliradian.arcMinute = mrad$moa = function(mrad) {
  return mrad * ((180 * 60) / (1000 * Math.PI)); // Milliradian to Minute of Arc
};

/* Radian Conversions */
convertAngle.radian.degree = rad$deg = function(rad) {
  return rad * (180 / Math.PI); // Radian to Degree
};

convertAngle.radian.gradian = rad$gad = function(rad) {
  return rad * (200 / Math.PI); // Radian to Gradian
};

convertAngle.radian.milliradian = rad$mrad = function(rad) {
  return rad * 1000; // Radian to Milliradian
};

convertAngle.radian.arcSecond = rad$soa = function(rad) {
  return rad * ((180 * 3600) / Math.PI); // Radian to Second of Arc
};

convertAngle.radian.arcMinute = rad$moa = function(rad) {
  return rad * ((180 * 60) / Math.PI); // Radian to Minute of Arc
};

/* Second of Arc Conversions */
convertAngle.arcSecond.degree = soa$deg = function(soa) {
  return soa / 3600; // Second of Arc to Degree
};

convertAngle.arcSecond.gradian = soa$gad = function(soa) {
  return soa / 3240; // Second of Arc to Gradian
};

convertAngle.arcSecond.milliradian = soa$mrad = function(soa) {
  return soa * ((1000 * Math.PI) / (180 * 3600)); // Second of Arc to Milliradian
};

convertAngle.arcSecond.radian = soa$rad = function(soa) {
  return soa * (Math.PI / (180 * 3600)); // Second of Arc to Radian
};

convertAngle.arcSecond.arcMinute = soa$moa = function(soa) {
  return soa / 60; // Second of Arc to Minute of Arc
};

/* Minute of Arc Conversions */
convertAngle.arcMinute.degree = moa$deg = function(moa) {
  return moa / 60; // Minute of Arc to Degree
};

convertAngle.arcMinute.gradian = moa$gad = function(moa) {
  return moa / 54; // Minute of Arc to Gradian
};

convertAngle.arcMinute.milliradian = moa$mrad = function(moa) {
  return moa * ((1000 * Math.PI) / (180 * 60)); // Minute of Arc to Milliradian
};

convertAngle.arcMinute.radian = moa$rad = function(moa) {
  return moa * (Math.PI / (180 * 60)); // Minute of Arc to Radian
};

convertAngle.arcMinute.arcSecond = moa$soa = function(moa) {
  return moa * 60; // Minute of Arc to Second of Arc
};