// Generated by CoffeeScript 2.7.0
/* Energy Conversions */

var convertEnergy, j$kj, j$kwh, j$wh, kj$j, kj$kwh, kj$wh, kwh$j, kwh$kj, kwh$wh, wh$j, wh$kj, wh$kwh;

convertEnergy = {
  joule: {},
  kilojoule: {},
  watt: {},
  kilowatt: {}
};

/* Joule Conversions */
convertEnergy.joule.kilojoule = j$kj = function(j) {
  return j / 1e+3; // Joule to Kilojoule
};

convertEnergy.joule.watt = j$wh = function(j) {
  return j / 36e+2; // Joule to Watt
};

convertEnergy.joule.kilowatt = j$kwh = function(j) {
  return j / 36e+5; // Joule to Kilowatt
};

/* Kilojoule Conversions */
convertEnergy.kilojoule.joule = kj$j = function(kj) {
  return kj * 1e+3; // Kilojoule to Joule
};

convertEnergy.kilojoule.watt = kj$wh = function(kj) {
  return kj / 3.6; // Kilojoule to Watt
};

convertEnergy.kilojoule.kilowatt = kj$kwh = function(kj) {
  return kj / 36e+2; // Kilojoule to Kilowatt
};

/* Watt Conversions */
convertEnergy.watt.joule = wh$j = function(wh) {
  return wh * 36e+2; // Watt to Joule
};

convertEnergy.watt.kilojoule = wh$kj = function(wh) {
  return wh * 3.6; // Watt to Kilojoule
};

convertEnergy.watt.kilowatt = wh$kwh = function(wh) {
  return wh / 1e+3; // Watt to Kilowatt
};

/* Kilowatt Conversions */
convertEnergy.kilowatt.joule = kwh$j = function(kwh) {
  return kwh * 36e+5; // Kilowatt to Joule
};

convertEnergy.kilowatt.kilojoule = kwh$kj = function(kwh) {
  return kwh * 36e+2; // Kilowatt to Kilojoule
};

convertEnergy.kilowattwatt.watt = kwh$wh = function(kwh) {
  return kwh * 1e+3; // Kilowatt to Watt
};