// Generated by CoffeeScript 2.7.0
/* Frequency Conversions */

var convertFrequency, ghz$hz, ghz$khz, ghz$mhz, hz$ghz, hz$khz, hz$mhz, khz$ghz, khz$hz, khz$mhz, mhz$ghz, mhz$hz, mhz$khz;

convertFrequency = {
  hertz: {},
  kilohertz: {},
  megahertz: {},
  gigahertz: {}
};

/* Hertz Conversions */
convertFrequency.hertz.kilohertz = hz$khz = function(hz) {
  return hz / 1e+3; // Hertz to Kilohertz
};

convertFrequency.hertz.megahertz = hz$mhz = function(hz) {
  return hz / 1e+6; // Hertz to Megahertz
};

convertFrequency.hertz.gigahertz = hz$ghz = function(hz) {
  return hz / 1e+9; // Hertz to Gigahertz
};

/* Kilohertz Conversions */
convertFrequency.kilohertz.hertz = khz$hz = function(khz) {
  return khz * 1e+3; // Kilohertz to Hertz
};

convertFrequency.kilohertz.megahertz = khz$mhz = function(khz) {
  return khz / 1e+3; // Kilohertz to Megahertz
};

convertFrequency.kilohertz.gigahertz = khz$ghz = function(khz) {
  return khz / 1e+6; // Kilohertz to Gigahertz
};

/* Megahertz Conversions */
convertFrequency.megahertz.hertz = mhz$hz = function(mhz) {
  return mhz * 1e+6; // Megahertz to Hertz
};

convertFrequency.megahertz.kilohertz = mhz$khz = function(mhz) {
  return mhz * 1e+3; // Megahertz to Kilohertz
};

convertFrequency.megahertz.gigahertz = mhz$ghz = function(mhz) {
  return mhz / 1e+3; // Megahertz to Gigahertz
};

/* Gigahertz Conversions */
convertFrequency.gigahertz.hertz = ghz$hz = function(ghz) {
  return ghz * 1e+9; // Gigahertz to Hertz
};

convertFrequency.gigahertz.kilohertz = ghz$khz = function(ghz) {
  return ghz * 1e+6; // Gigahertz to Kilohertz
};

convertFrequency.gigahertz.megahertz = ghz$mhz = function(ghz) {
  return ghz * 1e+3; // Gigahertz to Megahertz
};