name: Node CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test
